Add Match test
Optable/optable-pair-cli pull request #51
Opened 2024-12-06 15:10 UTC by mariiatuzovska

2024-12-06 19:20 UTC, amanjpro commented on pkg/pair/match_test.go
> +	expectContain := make(map[string]struct{}, 1000)
```suggestion
	expectContain := make(map[string]struct{}, 901)
```

It should be exactly 901 emails matched, no?

2024-12-06 19:20 UTC, amanjpro commented on pkg/pair/match_test.go
> +	require.Len(t, records, 800, "must contain 100 emails")
```suggestion
	require.Len(t, records, 800, "must contain 800 emails")
```

2024-12-09 16:04 UTC, juanli16 requested changes

2024-12-09 16:04 UTC, juanli16 commented on pkg/pair/match_test.go
> +		require.True(t, exists, "must exist in the hash-encrypted list")
```suggestion
		_, exists := expectContain[line[0]]
		require.True(t, exists, "must exist in the hash-encrypted list")
		delete(expectContain, line[0])
```

2024-12-09 16:04 UTC, juanli16 commented on pkg/pair/match_test.go
> +			require.True(t, exists, "must exist in the hash-encrypted list")
```suggestion
			_, exists := expectContain[line[0]]
			require.True(t, exists, "must exist in the hash-encrypted list")
			delete(expectContain, line[0])
```

2024-12-09 16:04 UTC, juanli16 commented on pkg/pair/match_test.go
> +
please use some constants instead

2024-12-09 16:04 UTC, juanli16 commented on pkg/pair/match_test.go
> +		require.True(t, exists, "must exist in the hash-encrypted list")
You don't want the same ID matching over and over again.

2024-12-09 17:49 UTC, merged